name: "Build amd64"

env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE: plucky

on:
  workflow_dispatch:
  schedule:
# Build Every Week
    - cron: "0 0 * * 0"
  push:
    branches: [ 'main' ]
    paths:
      - ".github/workflows/build-amd64.yml"


permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Needed Dependencies
        run: |
          sudo apt update && sudo apt install -yq curl libarchive-tools
          curl -L -o /tmp/mmdebstrap.deb http://ftp.us.debian.org/debian/pool/main/m/mmdebstrap/mmdebstrap_1.5.7-3_all.deb
          sudo apt install -yq /tmp/mmdebstrap.deb
          curl -L -o /tmp/keyring.deb http://ftp.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb
          sudo apt install -yq /tmp/keyring.deb
      - name: Build rootfs
        run: |
          dist_version="$RELEASE"
          sudo mmdebstrap \
          --arch=amd64 \
          --variant=apt \
          --components="main,universe,multiverse" \
          --include=locales,passwd,software-properties-common,ca-certificates \
          --format=tar \
          ${dist_version} \
          rootfs.tar.gz \
          http://archive.ubuntu.com/ubuntu

      - name: Combine wsldl and rootfs
        run: |
          curl -L https://github.com/yuk7/wsldl/releases/download/26032000/icons.zip -o icons.zip
          bsdtar -xf icons.zip
          mv Ubuntu.exe ubuntu-latest.exe
          bsdtar -a -cf ubuntu-latest.zip rootfs.tar.gz ubuntu-latest.exe
      - name: Push to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-amd64-${{ env.RELEASE }}
          name: Release amd64 ${{ env.RELEASE }}
          files: |
            ubuntu-latest.zip
            rootfs.tar.gz
          preserve_order: true
          make_latest: false